blocks:
  - name: Step2
    step:
      integration: javascript
      javascript:
        body: // Convert Array to SQL table
  - name: Step1
    step:
      integration: c00652f8-5dd0-499b-9f0e-c48909251229
      snowflake:
        body: |-
          -- Write rows to DUMMY_SUBMITTED_CODES with INSERTION_DATE timestamp '2024-04-22 03:12:23'
          -- DOwnload and email .csv file
        filterBy: []
        mappedColumns: []
        newValues: []
        oldValues: []
        usePreparedSql: true
metadata:
  id: 6c8de211-5dc2-4330-bccf-41b30e183ab3
  name: API1
  organization: 220afb9e-bf20-40ef-9f76-b8fe766a8630
trigger:
  application:
    id: 9823d11f-f535-4ca1-944b-46d06fe4df38
