blocks:
  - name: Step1
    step:
      integration: c00652f8-5dd0-499b-9f0e-c48909251229
      snowflake:
        body: |-
          SELECT 
            BC.*,
          FROM 
            PROD_WAREHOUSE.BILLING.CODES_TO_SUBMIT BC
        filterBy: []
        mappedColumns: []
        newValues: []
        oldValues: []
        usePreparedSql: true
metadata:
  id: 5e0b5918-2baf-4fbc-98cf-1630e1c40981
  name: getCharges
  organization: 220afb9e-bf20-40ef-9f76-b8fe766a8630
trigger:
  application:
    id: 9823d11f-f535-4ca1-944b-46d06fe4df38
