blocks:
  - name: Step1
    step:
      integration: c00652f8-5dd0-499b-9f0e-c48909251229
      snowflake:
        body: ""
        filterBy: []
        mappedColumns: []
        newValues: []
        oldValues: []
        usePreparedSql: true
metadata:
  id: e5f991a6-0b6e-46a4-9788-9fbaeccd2b0c
  name: submitCodes
  organization: 220afb9e-bf20-40ef-9f76-b8fe766a8630
trigger:
  application:
    id: 9823d11f-f535-4ca1-944b-46d06fe4df38
