blocks:
  - name: Step1
    step:
      integration: c00652f8-5dd0-499b-9f0e-c48909251229
      snowflake:
        body: |-
          SELECT 
            PROC_CODE AS CPT_CODE,
            SUM(APPLIED) AS Total_Payments,
            SUM(CHARGES) AS Total_Charges,
            SUM(APPLIED) * 0.8 AS Fee,
          FROM 
            FIVETRAN_DATABASE.SHARE_POINT.SEGUE_REIMBURSEMENTS_RPM_PAYMENTS
        filterBy: []
        mappedColumns: []
        newValues: []
        oldValues: []
        usePreparedSql: true
metadata:
  id: 0c929eb6-942d-4a9d-974b-741166aee532
  name: API1
  organization: 220afb9e-bf20-40ef-9f76-b8fe766a8630
trigger:
  application:
    id: 0628ed1a-5202-4cbe-829f-9b3976454a97
