blocks:
  - name: Step1
    step:
      integration: c00652f8-5dd0-499b-9f0e-c48909251229
      snowflake:
        body: SELECT * FROM FIVETRAN_DATABASE.BILLING.SEGUE_HISTORICAL_BILLINGS
        filterBy: []
        mappedColumns: []
        newValues: []
        oldValues: []
        usePreparedSql: true
metadata:
  id: 5b8f684e-e555-466f-b8d7-b0dace5ed67f
  name: getPreviousBillings
  organization: 220afb9e-bf20-40ef-9f76-b8fe766a8630
trigger:
  application:
    id: 0628ed1a-5202-4cbe-829f-9b3976454a97
