name: Sync changes to Superblocks
on: [push]

jobs:
  superblocks-sync:
    runs-on: ubuntu-latest
    name: Sync to Superblocks
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push
        uses: superblocksteam/import-action@v1
        id: push
        with:
          token: ${{ secrets.SUPERBLOCKS_TOKEN }}

      - name: Pull
        uses: superblocksteam/export-action@v1
        id: pull
        with:
          token: ${{ secrets.SUPERBLOCKS_TOKEN }}
